#!/bin/bash

# Sample submission script for Rmpi Hello World
# Make sure to change the -A line to your allocation

#PBS -l walltime=00:10:00
#PBS -l nodes=2:ppn=32
#PBS -W group_list=dragonstooth
#PBS -q normal_q
#PBS -A ascclass 

# Add modules
module purge
module load gcc openblas R/3.4.1
module load openmpi hdf5 netcdf R-parallel/3.4.1

# Change to the directory from which the job was submitted
cd $PBS_O_WORKDIR

# Run R
Rscript helloworld_rmpi.r

exit;
