---
title: 'STAT6984: Homework 2'
author: "Alexander Durbin"
date: "September 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 4
## NOT GETTING .RDATA FILES IN COMMAND LINE BUT SHOULD BE

- R CMD BATCH
    - Called with `R CMD BATCH [options] input_file output_file args`
    - By default produces a `.Rout` file with same name as `input_file`.
    - `.Rout` contains the input and output of running the commands in `input_file` in the `R` console.
    - Plots specified in `input_file` are placed in `Rplots.pdf` on separate pages.
    - Default options are to save `.Rdata` and restore previous `.Rdata` when running scripts. 
    - Does not write output to command line, `cat` arguments in `input_file` appear as console output in `.Rout`.
    - Execution of file is halted when error found in `.R` and no error output appears in console. Warnings are also not printed to console.
    - Can accept conole input using `args` option and `arg <- commandArgs(TRUE)` in `.R` file. Then can index `args` like a vector and assign the values as needed using `var <- eval(parse(text = arg[1]))`. Be clear to not put spaces in `args` as `stdin` uses `space` as a separator.
    
- Rscript
    - Called with `Rscript [options] [-e expr] file args`
    - `expr` is used in absence of `file` and will evaulate the command and print the output to the console.
    - Does not print console output from `file` unless it is a package conflict, warnings, or errors.
    - Also prints plots from `file` on separate pages to `Rplots.pdf`.
    - `args` are similarly used as in `R CMD BATCH` with the appropriate `commandArgs(TRUE)` statement.
    - Does not write to `.Rout` file by default or have options to. If wanting to capture the console output, will need to explicitly write to a file or use log files.
