---
title: "Homework 1"
author: "Alexander Durbin"
date: "August 30, 2017"
output: 
    pdf_document: 
        fig_caption: TRUE
        fig_width: 3
        fig_height: 2
---

# Problem 3

```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(tibble)
library(features)
```


```{r eval = TRUE, echo = FALSE, fig.cap = ' $f(x) = 1 - x +3x^2 - x^3$ '}

my_function <- function(x){
    eval <- 1 - x + 3*x^2 - x^3
    return(eval) 
}

raw <- tibble( x = seq(-0.5, 2.5, by = 0.01), y = my_function(x))

ggplot(raw) +
    geom_line(aes(x, y))

```

Evaluating $f(x) = 1 - x +3x^2 - x^3$ over $[-0.5, 2.5]$, we idenfy critical points near $0.2$ and $1.8$. Solving for the critical points by hand, we find $\frac{1}{3}(3 - \sqrt{6})$ and $\frac{1}{3}(3+\sqrt{6})$ are the critical points of the function. Additionally, we use the `features` library to numerically compute the critical points. The results are consistent with our graphic and the by-hand calculations.  

```{r, eval = TRUE}
ans <- features(raw$x, raw$y)
fget(ans)
```